### ISSUE TITLE
Add Cluster flag to group spec

### ISSUE THREAD

**Issue by rdodev** [rdodev/fastdriver#5]
SD groups support specifying whether the group will be monitoring a cluster. Add flag to spec as follows:

```
group-name:
 parent: blah
 cluster: yes
 conditions:
  ...
```
